export const UI_COPY = {
  title: "さんすうシューティング",
  subtitle: "あそびながら けいさんパワーをアップ",
  start: "スタート",
  backToTitle: "タイトルへ",
  playAgain: "もういちど あそぶ",
  soundOn: "おと: ON",
  soundOff: "おと: OFF",
  howToTitle: "あそびかた",
  howToLines: [
    "1. うえの もんだいを よもう",
    "2. したの 3つの すうじから こたえを えらぼう",
    "3. せいかいを うって てきを たおそう"
  ],
  controlsDesktop: "そうさ: ひだり みぎ で いどう / 1 2 3 か スペースで うつ",
  controlsMobile: "そうさ: ドラッグで いどう / したの すうじを タップ",
  question: "もんだい",
  stageClear: "ステージ クリア",
  gameOver: "チャレンジ おしまい",
  summaryTitle: "けっか はっぴょう",
  weakPointNone: "ぜんぶ バランスよく がんばれたよ",
  retryHint: "ミスした もんだいは、あとで また でやすく なっているよ",
  scoreLabel: "スコア",
  correctLabel: "せいかい",
  missLabel: "ミス",
  accuracyLabel: "せいとうりつ",
  weakPointLabel: "にがて かも",
  lifeLabel: "ライフ",
  comboLabel: "コンボ",
  roundLabel: "もんめ",
  timeoutMessage: "まにあわなかったよ。つぎは はやめに えらぼう",
  contactMessage: "てきが せまりすぎたよ。おちついて つぎへいこう",
  correctMessage: "ナイス。せいかい",
  wrongMessage: "おしい。つぎで 取りかえそう"
};
